### PR TITLE
Use Plack::App::DirectoryIndex instead of Plack::App::Directory

### PR DESCRIPTION
**Pull request by davorg**
Adds support for index.html.

### CODE REVIEW

**Comment by davorg** [comment]
Hi. Any thoughts on this PR?

**Comment by davorg** [comment]
Hi. If you're no longer interested in this module, would you consider giving me (DAVECROSS) co-maint on CPAN, so I can release the fixed version?

**Comment by oalders** [comment]
Would be great to see this code continue improving. I find myself coming back to it regularly.

**Comment by oalders** [comment]
@melo would it be possible to merge and release this or give permissions to @davorg?

**Comment by melo** [comment]
Merged and added @davorg as collaborator.

**Comment by davorg** [comment]
Thanks @melo.

How much input do you want on this going forward? Can I make whatever fixes and enhancements I want, or do you still want to approve changes?

**Comment by melo** [comment]
Hi @davorg,

please make any changes you think are required, no need for prior approval. I cannot dedicate much time to this due to work.

I appreciate your work on this.

Bye,

**Pull request merged**
